package me.doujiang.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF006B5E)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7CF8E1)
val md_theme_light_onPrimaryContainer = Color(0xFF00201B)
val md_theme_light_secondary = Color(0xFF4B635C)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE9DF)
val md_theme_light_onSecondaryContainer = Color(0xFF06201A)
val md_theme_light_tertiary = Color(0xFF426277)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC7E7FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E30)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF9)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF9)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDBE5DE)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4944)
val md_theme_light_outline = Color(0xFF6F7974)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1ED)
val md_theme_light_inverseSurface = Color(0xFF2E312F)
val md_theme_light_inversePrimary = Color(0xFF5EDBC5)
val md_theme_light_surfaceTint = Color(0xFF006B5E)
val md_theme_light_outlineVariant = Color(0xFFBFC9C2)
val md_theme_light_scrim = Color(0xFF000000)

// Dark theme colors
val md_theme_dark_primary = Color(0xFF5EDBC5)
val md_theme_dark_onPrimary = Color(0xFF003830)
val md_theme_dark_primaryContainer = Color(0xFF005146)
val md_theme_dark_onPrimaryContainer = Color(0xFF7CF8E1)
val md_theme_dark_secondary = Color(0xFFB2CCC3)
val md_theme_dark_onSecondary = Color(0xFF1D352E)
val md_theme_dark_secondaryContainer = Color(0xFF334B44)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE9DF)
val md_theme_dark_tertiary = Color(0xFFABCBE2)
val md_theme_dark_onTertiary = Color(0xFF0D3347)
val md_theme_dark_tertiaryContainer = Color(0xFF294A5E)
val md_theme_dark_onTertiaryContainer = Color(0xFFC7E7FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DF)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DF)
val md_theme_dark_surfaceVariant = Color(0xFF3F4944)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC9C2)
val md_theme_dark_outline = Color(0xFF89938D)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DF)
val md_theme_dark_inversePrimary = Color(0xFF006B5E)
val md_theme_dark_surfaceTint = Color(0xFF5EDBC5)
val md_theme_dark_outlineVariant = Color(0xFF3F4944)
val md_theme_dark_scrim = Color(0xFF000000)

// M3E surface container 色阶 — Light
val md_theme_light_surfaceBright = Color(0xFFFBFDF9)
val md_theme_light_surfaceDim = Color(0xFFE1E5E0)
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF5F8F4)
val md_theme_light_surfaceContainer = Color(0xFFEFF2EE)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9ECE8)
val md_theme_light_surfaceContainerHighest = Color(0xFFE3E7E2)

// M3E surface container 色阶 — Dark
val md_theme_dark_surfaceBright = Color(0xFF3F423F)
val md_theme_dark_surfaceDim = Color(0xFF191C1A)
val md_theme_dark_surfaceContainerLowest = Color(0xFF131614)
val md_theme_dark_surfaceContainerLow = Color(0xFF1E211F)
val md_theme_dark_surfaceContainer = Color(0xFF232624)
val md_theme_dark_surfaceContainerHigh = Color(0xFF2D302E)
val md_theme_dark_surfaceContainerHighest = Color(0xFF383B39)

// Status colors
val StatusRunning = Color(0xFF4CAF50)
val StatusWaiting = Color(0xFFFFA726)
val StatusDisabled = Color(0xFF9E9E9E)
val StatusError = Color(0xFFEF5350)
val StatusInstalling = Color(0xFF42A5F5)
